//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace API_IMC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblGenders
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tblGenders()
        {
            this.tblHistoricalEvaluations = new HashSet<tblHistoricalEvaluations>();
        }
    
        public int intPkIdGender { get; set; }
        public string strDescription { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblHistoricalEvaluations> tblHistoricalEvaluations { get; set; }
    }
}
