//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace API_IMC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblHistoricalEvaluations
    {
        public int intPkIdEvaluation { get; set; }
        public int intConsultationNumber { get; set; }
        public int intFkIdUser { get; set; }
        public int intFKIdGender { get; set; }
        public int intUserAge { get; set; }
        public double fltWeight { get; set; }
        public double fltHeight { get; set; }
        public string strBodyType { get; set; }
        public double fltBodyMass { get; set; }
        public string strObservations { get; set; }
        public System.DateTime dtmEvaluationDate { get; set; }
    
        public virtual tblGenders tblGenders { get; set; }
        public virtual tblUsers tblUsers { get; set; }
    }
}
